[package]
name = "cadenza-tree"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hashbrown.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
insta.workspace = true
