[package]
name = "cadenza-gcode"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build/main.rs"

[dependencies]
thiserror.workspace = true
miette.workspace = true

[dev-dependencies]
insta.workspace = true
