[package]
name = "cadenza-meta"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cadenza-tree = { path = "../cadenza-tree" }
proc-macro2.workspace = true
quote.workspace = true

[dev-dependencies]
insta.workspace = true
